### ISSUE TITLE
socketio.exceptions.ConnectionError: Already connected

### ISSUE THREAD

**Issue by PaxxPatriot** [PaxxPatriot/cheapbot#1]
After some time running, the following error can occur and the bot stops:
```
packet queue is empty, aborting
Traceback (most recent call last):
  File "C:\Users\lukas\skinport.py.bot\cheapbot.py", line 38, in <module>
    skinport_client.run()
  File "C:\Users\lukas\.virtualenvs\skinport.py.bot-mJRca_4D\lib\site-packages\skinport\client.py", line 132, in run
    return future.result()
  File "C:\Users\lukas\.virtualenvs\skinport.py.bot-mJRca_4D\lib\site-packages\skinport\client.py", line 111, in runner
    await self.connect(*args, **kwargs)
  File "C:\Users\lukas\.virtualenvs\skinport.py.bot-mJRca_4D\lib\site-packages\skinport\client.py", line 194, in connect
    await self.ws.connect("https://skinport.com", transports=["websocket"])
  File "C:\Users\lukas\.virtualenvs\skinport.py.bot-mJRca_4D\lib\site-packages\socketio\asyncio_client.py", line 117, in connect
    raise exceptions.ConnectionError('Already connected')
socketio.exceptions.ConnectionError: Already connected
```

**Comment by PaxxPatriot** [comment]
This was fixed by [skinport.py #4](https://github.com/PaxxPatriot/skinport.py/pull/4)
